<?php

namespace Blogger\BlogBundle\Entity\Repository;

/**
 * BiddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiddRepository extends \Doctrine\ORM\EntityRepository
{
}
