_security_login:
    path:  /login
    defaults: { _controller: "BloggerBlogBundle:Security:login" }

_security_check:
    path:  /login_check

_security_logout:
    path:  /logout

admin_home:
    path:  /admin/
    defaults: { _controller: "BloggerBlogBundle:Prepod:index" }
    requirements:
           methods:  GET

blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
